version: "3" 
services:
  view:
    container_name: "view" 
    build:
      context: ./view
      dockerfile: view.Dockerfile 
    volumes:
    - ./view:/view
    - ./view/node_modules:/view/node_modules
    command: /view/script/dev_up.sh
    ports:
    - "3000:3000"
    stdin_open: true
    tty: true 
    env_file:
      - ./view.env

  app:
    build:
      context: ./api
      dockerfile: api.Dockerfile
    entrypoint: ["/api/scripts/entrypoint.sh"]
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - "./api:/api"
      - "./api/db:/api/db"  # SQLite データベースをプロジェクトの `api/db` に保存
    ports:
      - "3001:3001"
    env_file:
      - ./api.env