prompt: |
  ユーザーの入力(怪物のストーリー)に基づいて、筋力、体力、精神力、敏捷性、外見、知性、サイズの7つのパラメータを生成してください。
  それぞれのパラメータは以下の基準に従って数値を決定してください。

  ### パラメータ生成基準
  1. **strength（筋力）**
      - 3~4: 身体は弱々しく、物理的な攻撃はほとんど無力。
      - 5~6: 動きは緩慢で、壊れやすい肉体。
      - 7~8: 肉体は普通だが、戦闘に不向き。
      - 9~12: 平均的な神話生物の強さ。
      - 13~14: 人間を容易に引き裂く強さ。
      - 15~16: 非常に強力、物理攻撃が極めて強力。
      - 17~18: 巨大な怪力を誇り、建物すら破壊できる。

  2. **constitution（体力）**
      - 3~4: 極めて脆弱で常に休息が必要な存在。
      - 5~6: 弱体化しており、すぐに倒れる。
      - 7~8: 持久力がなく、長時間活動できない。
      - 9~12: 平均的な耐久性を持つ。
      - 13~14: 神話的耐久性を持ち、ダメージを耐えやすい。
      - 15~16: 異常な耐久性を誇り、ほぼ不死に近い。
      - 17~18: 完全に不死身、どんな攻撃も耐えることができる。

  3. **power（精神力）**
      - 3: 常に狂気に支配され、不安定な存在。
      - 4: かつて恐るべき事件を目撃した結果、歪んだ存在。
      - 5~6: 外部からの刺激に極めて弱く、恐怖に満ちている。
      - 7~8: 精神的に脆弱で、簡単に打ち負かされる。
      - 9~12: 普通の精神力を持ち、神話的存在にとっては小さな脅威。
      - 13~14: 優れた精神力を持ち、神話生物に立ち向かう力を持つ。
      - 15~16: 神話生物にも負けない強靭な精神力。
      - 17: 精神的な鍛錬を積んだ存在、狂気の影響を無効化できる。
      - 18: 完全な精神安定、どんな邪悪な力も影響を与えられない。

  4. **dexterity（敏捷性）**
      - 3~4: 極めて遅く、肉体が不完全な存在。
      - 5~6: 緩慢な動きでほとんど移動できない。
      - 7~8: 平均的な速さだが、神話生物としては並。
      - 9~10: 非常に速く、人間を容易に追い詰める。
      - 11~12: 驚異的なスピードで走ることができる。
      - 13~14: ほぼ瞬間移動に近いスピードを持つ。
      - 15~16: 見る者の目に映らないほどの速さ。
      - 17~18: 時間を超越した動きが可能。

  5. **appearance（外見）**
      - 3~4: 異形の姿で見る者に恐怖や狂気をもたらす。
      - 5~6: 不気味な姿で、人間にとって忌避される外見。
      - 7~8: 奇怪な姿だが、ある程度親しみを感じる部分もある。
      - 9~12: 人間から見ても異常ではないが、特徴が捉えにくい姿。
      - 13~14: 異様だが、人間を魅了する何かを持っている。
      - 15~16: 美しさと異形が共存し、見る者を引きつける魅力を放つ。
      - 17~18: 異次元的な美しさや威厳を持ち、見る者は目が離せない。

  6. **intelligence（知性）**
      - 8~9: 本能に従い行動するが、深い思考は持たない。
      - 10~11: 単純な行動しか取れず、複雑な策略には向かない。
      - 12~13: 知的な存在だが、人間の知性と同等の思考力を持つ。
      - 14~15: 狡猾で策略を巡らし、相手を混乱させる。
      - 16~17: 神話生物の中でも特に知性が高く、異常な洞察力を持つ。
      - 18: 人間の理解を超えた天才的な知性を持ち、未来を見通す。

  7. **size（サイズ）**
      - 3~4: 極小で、隙間を通り抜けたり、敵の目を欺くことができる。
      - 5~6: 小柄で、素早く動き回るが、力は弱い。
      - 7~8: 小さな体を活かして、迅速に攻撃する。
      - 9~10: 成人男性と同程度のサイズ、バランスの取れた能力を持つ。
      - 11~12: 平均的なサイズ、標準的な力と敏捷性を持つ。
      - 13~14: 巨大な体格、威圧的な存在感を持つ。
      - 15~16: 非常に大きな体を持ち、圧倒的な力で相手を押し潰す。
      - 17~18: 神話的な巨体、並の生物では太刀打ちできない存在。

  出力形式：
  {
    "strength": "3~18の整数（筋力）",
    "constitution": "3~18の整数（体力）",
    "power": "3~18の整数（精神力）",
    "dexterity": "3~18の整数（敏捷性）",
    "appearance": "3~18の整数（外見）",
    "intelligence": "8~18の整数（知性）",
    "size": "3~18の整数（サイズ）"
  }