Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/*'

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/*'

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false